# Site settings
title: Mohamed Makthum Mohamed Ikbal
description: 'Software Engineer, technophile and an enthusiatic gamer.'
url: 'http://makthum.com'
baseurl: '/'
logo: makthum.jpg
disqus_shortname: makthum
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mohamed Makthum Mohamed Ikbal'
  email: makthum@gmail.com
  twitter_username: makthum_mohamed
  facebook_username: makthum.Mohamed
  github_username:  makthum 
  linkedin_username:  makthum

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
